### ISSUE TITLE
undefined method `timeout=' for Rack::Timeout:Class (NoMethodError)

### ISSUE THREAD

**Issue by polytronix** [heroku/rack-timeout#134]
rails g cancan:ability
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:90: warning: already initialized constant FileUtils::VERSION
/usr/local/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:92: warning: previous definition of VERSION was here
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1188: warning: already initialized constant FileUtils::Entry_::S_IF_DOOR
/usr/local/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1267: warning: previous definition of S_IF_DOOR was here
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1446: warning: already initialized constant FileUtils::Entry_::DIRECTORY_TERM
/usr/local/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1541: warning: previous definition of DIRECTORY_TERM was here
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1448: warning: already initialized constant FileUtils::Entry_::SYSCASE
/usr/local/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1543: warning: previous definition of SYSCASE was here
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1501: warning: already initialized constant FileUtils::OPT_TABLE
/usr/local/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1596: warning: previous definition of OPT_TABLE was here
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1555: warning: already initialized constant FileUtils::LOW_METHODS
/usr/local/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1650: warning: previous definition of LOW_METHODS was here
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1562: warning: already initialized constant FileUtils::METHODS
/usr/local/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1657: warning: previous definition of METHODS was here
WARNING: Nokogiri was built against LibXML version 2.9.4, but has dynamically loaded 2.8.0
Traceback (most recent call last):
	43: from bin/rails:4:in `<main>'
	42: from bin/rails:4:in `require'
	41: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	40: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	39: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:50:in `generate'
	38: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
	37: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	36: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
	35: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	34: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	33: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	32: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	31: from /Users/StephanieApril/Documents/Current Website/pcms/config/environment.rb:5:in `<top (required)>'
	30: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
	29: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
	28: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	27: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	26: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	25: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
	24: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
	23: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	22: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	21: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:415:in `call'
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
	19: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
	18: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	17: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	16: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	15: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	14: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/Users/StephanieApril/Documents/Current Website/pcms/config/initializers/timeout.rb:1:in `<top (required)>': undefined method `timeout=' for Rack::Timeout:Class (NoMethodError)

**Comment by polytronix** [comment]
thank you! had a moment.
