### ISSUE TITLE
undefined method `state=' for nil:NilClass

### ISSUE THREAD

**Issue by nadavshatz** [heroku/rack-timeout#57]
I'm getting the following error:

using 0.1.0 on JRuby 1.7.16

```rb
NoMethodError: undefined method `state=' for nil:NilClass
  rack/timeout.rb:148:in `_set_state!'
    env[ENV_INFO_KEY].state = state
  rack/timeout.rb:98:in `call'
    RT._set_state! env, :active
  org/jruby/RubyKernel.java:1501:in `loop'
  rack/timeout.rb:94:in `call'
    loop do
```

**Comment by kch** [comment]
Closing for now. Please reopen if you can repro.

**Comment by samandmoore** [comment]
Seeing a similar issue on jruby 1.7.19 using puma 2.15.3 and rack-timeout 0.3.2.

```
NoMethodError: undefined method `state' for nil:NilClass
               log_state_change at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/logging-observer.rb:41
                           call at org/jruby/RubyProc.java:271
  notify_state_change_observers at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:192
                           each at org/jruby/RubyArray.java:1613
  notify_state_change_observers at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:192
                    _set_state! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:169
                           call at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:115
                           call at org/jruby/RubyProc.java:271
                           call at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:117
                           call at org/jruby/RubyProc.java:271
                           run! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:39
                           run! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:52
                      run_loop! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:99
                           each at org/jruby/RubyArray.java:1613
                      run_loop! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:99
                           loop at org/jruby/RubyKernel.java:1507
                      run_loop! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:80
                         runner at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:72
```

It also appears to have resulted / coincided with a crash in the puma process. could be an out of memory issue?

**Comment by DSAMPAT** [comment]
@samandmoore This has been re-opened on issues #92

**Comment by samandmoore** [comment]
Thanks @DSAMPAT I will follow along there.
