### ISSUE TITLE
rack-timeout-0.2.3: Rack app error: #<NoMethodError: undefined method `info' for true:TrueClass>

### ISSUE THREAD

**Issue by PetrKaleta** [heroku/rack-timeout#71]
rack-timeout-0.2.3 on Heroku with jRuby 1.7.19

```
Rack app error: #<NoMethodError: undefined method `info' for true:TrueClass>
/app/vendor/bundle/jruby/1.9/gems/rack-timeout-0.2.3/lib/rack/timeout/logger.rb:46:in `log_state_change'
org/jruby/RubyProc.java:271:in `call'
/app/vendor/bundle/jruby/1.9/gems/rack-timeout-0.2.3/lib/rack/timeout.rb:176:in `notify_state_change_observers'
org/jruby/RubyArray.java:1613:in `each'
/app/vendor/bundle/jruby/1.9/gems/rack-timeout-0.2.3/lib/rack/timeout.rb:176:in `notify_state_change_observers'
/app/vendor/bundle/jruby/1.9/gems/rack-timeout-0.2.3/lib/rack/timeout.rb:153:in `_set_state!'
/app/vendor/bundle/jruby/1.9/gems/rack-timeout-0.2.3/lib/rack/timeout.rb:115:in `call'
/app/vendor/bundle/jruby/1.9/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/app/vendor/bundle/jruby/1.9/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:63:in `call'
/app/vendor/bundle/jruby/1.9/gems/puma-2.11.1-java/lib/puma/configuration.rb:82:in `call'
/app/vendor/bundle/jruby/1.9/gems/puma-2.11.1-java/lib/puma/server.rb:507:in `handle_request'
/app/vendor/bundle/jruby/1.9/gems/puma-2.11.1-java/lib/puma/server.rb:505:in `handle_request'
/app/vendor/bundle/jruby/1.9/gems/puma-2.11.1-java/lib/puma/server.rb:375:in `process_client'
/app/vendor/bundle/jruby/1.9/gems/puma-2.11.1-java/lib/puma/server.rb:371:in `process_client'
/app/vendor/bundle/jruby/1.9/gems/puma-2.11.1-java/lib/puma/server.rb:262:in `run'
org/jruby/RubyProc.java:271:in `call'
/app/vendor/bundle/jruby/1.9/gems/puma-2.11.1-java/lib/puma/thread_pool.rb:104:in `spawn_thread'
```

**Comment by kch** [comment]
fixed in https://github.com/heroku/rack-timeout/commit/6d0888197b2948356dbe57142d954e2243133e5d
